// Product detail page: product/<product-id>/ (generated by catalog-src/build.py).
// The page already contains the product content and metadata; this script adds the
// labelled specifications, FAQ, related products and the quote/save actions.
const pid = document.body.dataset.product;
const product = productById[pid];

function renderMissing() {
  document.title = "Product not found | SikandarTech";
  $("pdp").innerHTML = `<div class="empty" style="margin:60px 0">
    <h1 style="font-family:var(--f-display);font-size:1.6rem;margin-bottom:10px">Product not found</h1>
    <p>This product link is no longer valid. Browse the shop, or ask us on WhatsApp and we will source it.</p>
    <div class="state-actions"><a class="btn" href="${URLS.shop()}">Browse the shop</a>
    <a class="btn btn-line" href="${waLink("Hello SikandarTech,\n\nI am looking for a product that I could not find on your website. Could you please help me source it?\n\nThank you.")}" target="_blank" rel="noopener">Ask on WhatsApp</a></div></div>`;
}

function render(p) {
  const c = catById[p.cat];
  if (FINE_POINTER) {
    $("pdp-stage").addEventListener("pointermove", (e) => {
      const r = e.currentTarget.getBoundingClientRect();
      e.currentTarget.style.setProperty("--zx", ((e.clientX - r.left) / r.width) * 100 + "%");
      e.currentTarget.style.setProperty("--zy", ((e.clientY - r.top) / r.height) * 100 + "%");
    });
  }
  $("pdp-status").innerHTML = statusTag(p);
  $("pdp-code").textContent = productCode(p);
  $("pdp-lead").textContent = p.desc;
  $("pdp-highlights").innerHTML = specRows(p)
    .map(([k, v]) => `<li><span>${esc(k)}</span><strong>${esc(v)}</strong></li>`)
    .join("");

  $("pdp-overview").innerHTML = overview(p).map((t) => `<p>${esc(t)}</p>`).join("") +
    `<h3>Key features</h3><ul class="feature-list">${p.specs.map((s) => `<li>${iconSvg("check")}<span>${esc(s)}</span></li>`).join("")}</ul>`;
  $("pdp-ideal").innerHTML = idealFor(p).map((t) => `<li>${esc(t)}</li>`).join("");
  $("pdp-notes").innerHTML = productNotes(p).map((n) => `<p class="pdp-note">${esc(n)}</p>`).join("");

  const row = ([k, v]) => `<tr><th scope="row">${esc(k)}</th><td>${esc(v)}</td></tr>`;
  $("pdp-specs").innerHTML = [["Product", p.name], ["Type", c.name], ...specRows(p)].map(row).join("");
  $("pdp-sourcing").innerHTML = sourcingRows(p).map(row).join("");
  $("pdp-faq").innerHTML = productFaq(p)
    .map(([q, a], i) => `<details${i === 0 ? " open" : ""}><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`)
    .join("");

  // Same order as the generated page: the next products in the catalogue, then the earlier ones
  const related = PRODUCTS.filter((x) => x.cat === p.cat && x.id !== p.id);
  const idx = related.findIndex((x) => PRODUCTS.indexOf(x) > PRODUCTS.indexOf(p));
  const unique = (idx < 0 ? related : [...related.slice(idx), ...related.slice(0, idx)]).slice(0, 4);
  $("pdp-related").innerHTML = unique.map((x, i) => productCard(x)).join("");

  const waBtn = $("pdp-wa");
  waBtn.href = waLink(productMessage(p, 1));
  // Keep the quantity in the WhatsApp message in step with the selector
  const syncWa = () => (waBtn.href = waLink(productMessage(p, Math.max(1, parseInt($("qty").value, 10) || 1))));

  // Quantity + quote
  const qty = $("qty");
  const clamp = () => { qty.value = Math.max(1, Math.min(999999, parseInt(qty.value, 10) || 1)); syncWa(); };
  $("qty-minus").onclick = () => { qty.value = (parseInt(qty.value, 10) || 1) - 1; clamp(); };
  $("qty-plus").onclick = () => { qty.value = (parseInt(qty.value, 10) || 1) + 1; clamp(); };
  qty.addEventListener("change", clamp);
  qty.addEventListener("input", syncWa);
  $("pdp-quote").addEventListener("click", (e) => {
    clamp();
    Store.addQuote(p.id, Number(qty.value));
    toast(`${qty.value} × ${p.name} added to quote list`, { label: "View", run: () => openDrawer("quote") });
    const b = e.currentTarget;
    b.classList.add("is-added");
    b.innerHTML = `${iconSvg("check")}Added`;
    setTimeout(() => { b.classList.remove("is-added"); b.textContent = "Add to quote list"; }, 1400);
  });

  const save = $("pdp-save");
  const syncSave = () => {
    const on = Store.isSaved(p.id);
    save.classList.toggle("is-on", on);
    save.setAttribute("aria-pressed", on);
    save.setAttribute("aria-label", on ? "Remove from saved" : "Save");
  };
  save.onclick = () => { const on = Store.toggleSave(p.id); syncSave(); toast(on ? "Saved on this device" : "Removed from saved"); };
  syncSave();

  $("pdp-print").onclick = () => window.print();
  $("pdp-share").onclick = async () => {
    const url = document.querySelector('link[rel="canonical"]').href;
    try {
      if (navigator.share && !FINE_POINTER) await navigator.share({ title: p.name, url });
      else { await navigator.clipboard.writeText(url); toast("Link copied"); }
    } catch { /* user cancelled */ }
  };

  // Highlight the section in view
  const tabs = [...document.querySelectorAll(".pdp-tabs a")];
  if ("IntersectionObserver" in window) {
    const io = new IntersectionObserver((es) => es.forEach((en) => {
      if (en.isIntersecting) tabs.forEach((t) => t.classList.toggle("active", t.getAttribute("href") === "#" + en.target.id));
    }), { rootMargin: "-30% 0px -60% 0px" });
    ["overview", "specs", "sourcing", "faq"].forEach((id) => io.observe($(id)));
  }
}

if (product) render(product);
else renderMissing();
observeReveals();
