import heroJson from "./hero.json";

/**
 * Site-wide configuration. Everything brand- or policy-specific lives here so it
 * can be edited (or loaded from a CMS) without touching components.
 */
export const site = {
  name: "SUPER MIMIC",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://supermimic.net",
  tagline: "Looks real. Feels yours.",
  pillars: "Luxury. Precision. Detail.",
  description:
    "Super Mimic is a house of curated objects — shoes, watches, bags and accessories designed with precision and finished with restraint.",
  currency: "USD" as const,
  /** Prices are hidden across the storefront (cards, PDP, search, bag, checkout, filters, sorting,
   *  structured data). Product records keep their price for internal use; set true to show them again. */
  showPrices: false,
  freeShippingThreshold: 100,
  flatShippingRate: 5,
  shippingNote: "Complimentary delivery. Our concierge confirms timing with you.",
  returnsNote: "Returns and exchanges within 14 days of delivery.",
  dispatchNote: "Orders are dispatched within 24–48 hours.",
  /** GO-LIVE: confirm this mailbox exists (also used in data/pages.ts → Contact). */
  contactEmail: "concierge@supermimic.net",
  /** GO-LIVE PLACEHOLDERS: these point at each platform's home page, not a Super Mimic account.
   *  Replace each href with the real profile URL (or remove the entry) before launch. */
  social: [
    { label: "Instagram", href: "https://instagram.com/" },
    { label: "TikTok", href: "https://tiktok.com/" },
    { label: "Pinterest", href: "https://pinterest.com/" },
    { label: "YouTube", href: "https://youtube.com/" },
  ],
  nav: [
    { label: "Shop All", href: "/products" },
    { label: "New Arrivals", href: "/collections/new-arrivals" },
    { label: "Collections", href: "/collections", menu: "collections" as const },
    { label: "Categories", href: "/categories", menu: "categories" as const },
    { label: "Featured", href: "/collections/featured" },
    { label: "About", href: "/about" },
  ],
  popularSearches: ["Runner", "Automatic", "Tote", "Chelsea", "Leather", "GMT"],
};

/**
 * Hero campaign scenes. Each scene can be an image (Ken Burns) or a video.
 * To add UGC / campaign film: set `type: "video"`, `src` (MP4/WebM, 16:9),
 * `mobileSrc` (9:16) and keep `poster` as the first frame.
 */
export type HeroScene = {
  id: string;
  type: "image" | "video";
  src: string;
  mobileSrc?: string;
  /** Optional VP9/WebM alternative, offered before the MP4. */
  webm?: string;
  /** The video carries its own soundtrack; the hero Sound toggle unmutes it. */
  audio?: boolean;
  poster?: string;
  caption: string;
  /** Category id of the featured product (shown with the caption). */
  category?: string;
  href?: string;
  /** Tone of the frame so overlays can adapt. */
  tone: "dark" | "light";
  /** How long the scene stays before the next one (ms). Default 6500. */
  durationMs?: number;
  /** Hold the CTA back until this many ms into the scene (it fades in). */
  ctaDelayMs?: number;
  /** Videos loop by default; set false to hold the last frame. */
  loop?: boolean;
};

/** Generated by `npm run catalog:build` from data/hero-plan.json — every caption/link traces to a live product. */
/** Product stills generated by `npm run catalog:build` (kept for reference; not shown). */
export const productHeroScenes: HeroScene[] = heroJson as HeroScene[];

/** Hero: four studio looks on the pearl backdrop (from the campaign reel). Each has `tone: "light"`,
 *  so the header and text turn dark. The earlier dark product film is still in public/media/hero/
 *  (film.mp4) — add it back as a `type: "video"` scene with `tone: "dark"` if you want it in the rotation. */
export const heroScenes: HeroScene[] = [
  // The campaign film: model walks in, golden light swirl changes the outfit, bag and watch close-ups,
  // light sweep, final pose — then the "Explore collection" pill fades in (as in the reference reel).
  { id: "film", type: "video", src: "/media/hero/studio-film.mp4", webm: "/media/hero/studio-film.webm", poster: "/media/hero/studio-film-poster.webp", caption: "Campaign film", tone: "light", audio: true, loop: false, durationMs: 14500, ctaDelayMs: 8900, href: "/collections/all" },
  { id: "look-1", type: "image", src: "/media/hero/studio-01.webp", caption: "Cream knit, tailored trousers", tone: "light", href: "/collections/all" },
  { id: "look-2", type: "image", src: "/media/hero/studio-02.webp", caption: "Henley and wide-leg denim", tone: "light", href: "/collections/all" },
  { id: "look-3", type: "image", src: "/media/hero/studio-03.webp", caption: "Dark denim, structured tote", tone: "light", href: "/collections/all" },
  { id: "look-4", type: "image", src: "/media/hero/studio-04.webp", caption: "Overshirt and crossbody", tone: "light", href: "/collections/all" },
];

/** Optional ambient soundtrack (licensed MP3/OGG). If empty, a soft generative pad is used. */
/** Full-screen opening film shown once per session before the site (components/intro). */
export const intro = { enabled: true, src: "/media/intro/intro.mp4", tryAudio: true, maxWaitMs: 4000, maxTotalMs: 14000 };

/** Window event the hero fires when the visible scene changes, so the header can flip between light and dark text. */
export const HERO_TONE_EVENT = "sm-hero-tone";

export const heroAudio = { src: "", volume: 0.35 };

export const signatureStages = [
  { index: "01", title: "Eyewear", heading: "Seen, quietly.", body: "Hand-polished acetate in warm tortoise, with graduated tinted lenses. Frames that sit lightly and photograph beautifully.", image: "/media/signature/stage-01.webp" },
  { index: "02", title: "Sneaker", heading: "Quiet confidence, underfoot.", body: "Soft pebbled leather and suede panels on a clean cupsole. A contemporary sneaker that dresses up as easily as it dresses down.", image: "/media/signature/stage-02.webp" },
  { index: "03", title: "Handbag", heading: "Structure, with intent.", body: "A top-handle bag in full-grain cognac leather, closed with a brass padlock and finished with hand-painted edges.", image: "/media/signature/stage-03.webp" },
  { index: "04", title: "Watch", heading: "Precision you can feel.", body: "Brushed and polished steel, a slate sunburst dial and a small seconds subdial. Finished by hand, worn all day.", image: "/media/signature/stage-04.webp" },
  { index: "05", title: "Tailoring", heading: "Cut to hold its line.", body: "A single-button blazer in dense twill with peak lapels and pick-stitched edges, made to keep its shape from morning to night.", image: "/media/signature/stage-05.webp" },
  { index: "06", title: "Shoulder bag", heading: "Softness, resolved.", body: "Supple chocolate leather, a buckle strap and brass hardware, with an adjustable strap that carries as easily as it looks.", image: "/media/signature/stage-06.webp" },
  { index: "07", title: "Footwear", heading: "The high-top, refined.", body: "Smooth leather and brushed suede panels, a padded collar, a stitched cupsole and tonal waxed laces.", image: "/media/signature/stage-07.webp" },
  { index: "08", title: "Statement", heading: "The one you keep.", body: "A rose-gold case, a smoked chocolate dial and a hand-stitched leather strap. A watch made to be handed down.", image: "/media/signature/stage-08.webp" },
];
