#!/usr/bin/env python3
"""Build catalog.js and icons.js from the catalogue text files.

Usage:  python3 catalog-src/build.py [path/to/tabler/icons/outline]

Product photos: drop images/products/<product-id>.jpg (or .webp/.png) and
re-run; the product will use the photo instead of the illustration.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
ICON_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "tabler-outline")
STATUS = {"A": "available", "C": "coming", "E": "emerging"}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def load_icon(name):
    path = os.path.join(ICON_DIR, name + ".svg")
    if not os.path.exists(path):
        return None
    svg = open(path).read()
    body = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    body = re.sub(r'<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*/>', "", body)
    return re.sub(r"\s+", " ", body).strip()


categories, products, seen, errors = [], [], {}, []
photo_dir = os.path.join(SITE, "images", "products")
photos = {
    os.path.splitext(f)[0]: f
    for f in (os.listdir(photo_dir) if os.path.isdir(photo_dir) else [])
    if f.lower().endswith((".jpg", ".jpeg", ".webp", ".png"))
}

hero_dir = os.path.join(SITE, "images", "hero")
hero = next((f for f in sorted(os.listdir(hero_dir)) if f.lower().startswith("hero.") and f.lower().endswith((".png", ".webp", ".jpg", ".jpeg"))), None) if os.path.isdir(hero_dir) else None

cat_dir = os.path.join(SITE, "images", "categories")
cat_photos = {
    os.path.splitext(f)[0]: f
    for f in (os.listdir(cat_dir) if os.path.isdir(cat_dir) else [])
    if f.lower().endswith((".jpg", ".jpeg", ".webp", ".png"))
}

for fname in sorted(f for f in os.listdir(HERE) if f.endswith(".txt")):
    cat = None
    for n, line in enumerate(open(os.path.join(HERE, fname)), 1):
        line = line.strip()
        if not line:
            continue
        if line.startswith("#"):
            parts = [p.strip() for p in line[1:].split("|")]
            if len(parts) == 5 and re.fullmatch(r"[a-z0-9-]+", parts[0]):
                cslug, name, icon, color, tagline = parts
                cat = {"id": cslug, "name": name, "icon": icon, "color": color, "tagline": tagline}
                if cslug in cat_photos:
                    cat["photo"] = "images/categories/" + cat_photos[cslug]
                categories.append(cat)
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) != 5 or cat is None:
            errors.append(f"{fname}:{n}: bad line")
            continue
        name, icon, status, desc, specs = parts
        key = name.lower()
        if key in seen:
            errors.append(f"{fname}:{n}: duplicate '{name}' (also in {seen[key]})")
            continue
        seen[key] = cat["id"]
        pid = slug(name)
        p = {
            "id": pid,
            "cat": cat["id"],
            "name": name,
            "icon": icon,
            "status": STATUS[status],
            "desc": desc,
            "specs": [s.strip() for s in specs.split(";") if s.strip()],
        }
        if pid in photos:
            p["photo"] = "images/products/" + photos[pid]
        products.append(p)

# Interface icons used by the site scripts
UI_ICONS = ["heart", "shopping-bag", "arrow-right", "arrow-up-right", "menu", "x", "search", "eye",
            "player-play", "player-pause", "volume", "volume-off", "upload", "brand-whatsapp",
            "brand-tiktok", "brand-instagram", "brand-facebook", "check", "layout-grid", "plus", "minus"]

icons = {}
for name in sorted({c["icon"] for c in categories} | {p["icon"] for p in products} | set(UI_ICONS)):
    body = load_icon(name)
    if body is None:
        errors.append(f"missing icon: {name}")
    else:
        icons[name] = body

for c in categories:
    c["count"] = sum(1 for p in products if p["cat"] == c["id"])

if errors:
    print("\n".join(errors))
    sys.exit(1)

header = "// Generated by catalog-src/build.py. Edit the .txt files there, not this file.\n"
with open(os.path.join(SITE, "catalog.js"), "w") as f:
    f.write(header)
    f.write("const SITE_MEDIA = " + json.dumps({"hero": "images/hero/" + hero if hero else ""}) + ";\n")
    f.write("const CATEGORIES = " + json.dumps(categories, ensure_ascii=False, indent=1) + ";\n")
    f.write("const PRODUCTS = " + json.dumps(products, ensure_ascii=False, separators=(",", ":")).replace('},{', '},\n{') + ";\n")
with open(os.path.join(SITE, "icons.js"), "w") as f:
    f.write(header + "// Icons: Tabler Icons (MIT License, https://tabler.io/icons)\n")
    f.write("const ICONS = " + json.dumps(icons, separators=(",", ":")).replace('","', '",\n"') + ";\n")

print(f"{len(categories)} categories, {len(products)} products, {len(icons)} icons, {len(photos)} product photos, {len(cat_photos)} category photos, hero: {hero or 'none'}")
