"""Static page generator for SikandarTech (called by build.py).

Writes crawlable pages with real URLs, unique metadata and structured data:
  shop/                      full catalogue
  category/<id>/             one page per category
  product/<id>/              one page per product
  privacy/, terms/, shipping-returns/
  404.html
and keeps the shared header and footer of index.html and ugc.html in sync.
The old query-string pages (products.html, product.html) become redirects.
"""
import html
import json
import os
import re

SITE_URL = "https://sikandartech.com/"
STATUS_LABEL = {"available": "Available now", "coming": "Coming soon", "emerging": "Emerging tech"}
STATUS_SCHEMA = {"available": "Available now", "coming": "Coming soon", "emerging": "Emerging technology"}
FOOTER_CATS = ["ai-gadgets", "audio", "wearables", "drones-robotics", "gaming", "smart-home"]
DEFAULT_OG = "images/hero/hero.webp"
e = lambda s: html.escape(str(s), quote=True)


def code(products, p):
    return "ST-" + str(products.index(p) + 1).zfill(4)


def trim(text, n=158):
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= n else text[: n - 1].rsplit(" ", 1)[0].rstrip(",;:") + "…"


# ---------------------------------------------------------------- partials
def head(r, title, desc, path, og_image=DEFAULT_OG, robots=None, ld=(), extra=""):
    canonical = SITE_URL + path
    lds = "".join(
        f'\n  <script type="application/ld+json">{json.dumps(x, ensure_ascii=False, separators=(",", ":"))}</script>'
        for x in ld
    )
    robots_tag = f'\n  <meta name="robots" content="{robots}">' if robots else ""
    return f"""<!doctype html>
<html lang="en" data-root="{r}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{e(title)}</title>
  <meta name="description" content="{e(desc)}">{robots_tag}
  <meta name="theme-color" content="#ffffff">
  <link rel="canonical" href="{canonical}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="SikandarTech">
  <meta property="og:title" content="{e(title)}">
  <meta property="og:description" content="{e(desc)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{SITE_URL}{og_image}">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="preload" href="{r}fonts/unbounded-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="preload" href="{r}fonts/inter-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="icon" href="{r}favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="{r}style.css">{extra}
  <script>document.documentElement.classList.add("js")</script>{lds}
</head>"""


def header(r, active=""):
    home = r or "./"
    anchor = r  # "" on the home page, so links become "#about"

    def link(href, label, key):
        cur = ' class="active" aria-current="page"' if key and key == active else ""
        return f'<a href="{href}"{cur}>{label}</a>'

    return f"""<!-- @header (generated by catalog-src/build.py) -->
  <header class="header">
    <div class="container nav">
      <a href="{home}" class="logo" aria-label="SikandarTech home"><span class="logo-mark" aria-hidden="true">ST</span><span class="logo-text" aria-hidden="true">Sikandar<span>Tech</span></span></a>
      <nav class="nav-links" id="nav-links" aria-label="Main">
        {link(r + "shop/", "Shop", "shop")}
        {link(anchor + "#categories", "Categories", "")}
        {link(r + "ugc.html", "Community", "community")}
        {link(anchor + "#about", "About", "")}
        {link(anchor + "#contact", "Contact", "")}
      </nav>
      <div class="nav-actions">
        <a class="icon-btn" href="{r}shop/#search" aria-label="Search products" data-ui-icon="search"></a>
        <button class="icon-btn nav-saved" type="button" data-open-drawer="saved" aria-label="Saved products"><span data-ui-icon="heart"></span><span class="count" data-count="saved"></span></button>
        <button class="icon-btn" type="button" data-open-drawer="quote" aria-label="Quote list"><span data-ui-icon="shopping-bag"></span><span class="count" data-count="quote"></span></button>
        <button class="icon-btn nav-toggle" type="button" aria-label="Menu" aria-expanded="false" aria-controls="nav-links" data-ui-icon="menu"></button>
      </div>
    </div>
  </header>
  <!-- /@header -->"""


def footer(r, cat_by_id):
    home = r or "./"
    anchor = r
    cats = "".join(f'<li><a href="{r}category/{c}/">{e(cat_by_id[c]["name"])}</a></li>' for c in FOOTER_CATS if c in cat_by_id)
    return f"""<!-- @footer (generated by catalog-src/build.py) -->
  <footer class="footer">
    <div class="container">
      <div class="footer-top">
        <div class="footer-brand">
          <a href="{home}" class="logo" aria-label="SikandarTech home"><span class="logo-mark" aria-hidden="true">ST</span><span class="logo-word" aria-hidden="true">Sikandar<span>Tech</span></span></a>
          <p>Advanced tech and gadgets sourced direct from manufacturers in Guangzhou and Shenzhen, inspected before shipping and delivered worldwide.</p>
          <ul class="footer-social">
            <li><a data-social="instagram" target="_blank" rel="noopener" aria-label="Instagram" data-ui-icon="brand-instagram"></a></li>
            <li><a data-social="tiktok" target="_blank" rel="noopener" aria-label="TikTok" data-ui-icon="brand-tiktok"></a></li>
            <li><a data-social="facebook" target="_blank" rel="noopener" aria-label="Facebook" data-ui-icon="brand-facebook"></a></li>
            <li><a data-wa target="_blank" rel="noopener" aria-label="WhatsApp" data-ui-icon="brand-whatsapp"></a></li>
          </ul>
        </div>
        <div><h2>Shop</h2><ul>{cats}<li><a href="{r}shop/">All products</a></li></ul></div>
        <div><h2>Company</h2><ul><li><a href="{anchor}#about">About</a></li><li><a href="{anchor}#process">How it works</a></li><li><a href="{r}ugc.html">Community</a></li><li><a href="{anchor}#contact">Contact</a></li></ul></div>
        <div><h2>Help</h2><ul><li><a href="{r}shipping-returns/">Shipping &amp; returns</a></li><li><a href="{r}privacy/">Privacy policy</a></li><li><a href="{r}terms/">Terms of service</a></li><li><a data-wa target="_blank" rel="noopener">Ask on WhatsApp</a></li></ul></div>
      </div>
      <div class="footer-bottom"><span>© <span data-year>2026</span> SikandarTech</span><span>Guangzhou, China · Shipping worldwide</span></div>
    </div>
  </footer>
  <!-- /@footer -->"""


def tail(r, scripts):
    files = ["icons.js", "catalog.js", "script.js", "shop-core.js", "product-info.js"] + scripts
    tags = "\n  ".join(f'<script src="{r}{f}"></script>' for f in files)
    return f"""
  <aside class="wa-aside" aria-label="WhatsApp chat"><a class="whatsapp-float" data-wa target="_blank" rel="noopener" aria-label="Chat on WhatsApp" data-ui-icon="brand-whatsapp"></a></aside>

  {tags}
</body>
</html>
"""


def page(r, head_html, body_cls, main, cat_by_id, scripts=(), active="", body_attrs=""):
    return (
        head_html
        + f'\n<body class="{body_cls}"{body_attrs}>\n  <a class="skip-link" href="#main">Skip to content</a>\n\n  '
        + header(r, active)
        + "\n\n"
        + main
        + "\n\n  "
        + footer(r, cat_by_id)
        + tail(r, list(scripts))
    )


def write(site, rel, text):
    path = os.path.join(site, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


# ---------------------------------------------------------------- pieces
def art(r, p, cat, eager=False):
    c = cat["color"]
    if p.get("photo"):
        load = 'fetchpriority="high"' if eager else 'loading="lazy"'
        return f'<div class="art photo" style="--c:{c}"><img src="{r}{p["photo"]}" alt="{e(p["name"])}" width="600" height="600" {load} decoding="async"></div>'
    return f'<div class="art" style="--c:{c}" role="img" aria-label="{e(p["name"])}"></div>'


def simple_card(r, p, cat):
    return f"""<article class="p-card" data-id="{p['id']}">
      <a href="{r}product/{p['id']}/" aria-label="{e(p['name'])}: product details">{art(r, p, cat)}</a>
      <div class="p-body">
        <div class="p-meta"><span class="p-cat">{e(cat['name'])}</span><span class="status {p['status']}">{STATUS_LABEL[p['status']]}</span></div>
        <h3><a href="{r}product/{p['id']}/">{e(p['name'])}</a></h3>
        <p class="p-desc">{e(p['desc'])}</p>
      </div>
    </article>"""


def cat_links(r, categories, products, active):
    def item(href, cid, name, count, color):
        cur = ' active" aria-current="page' if cid == active else ""
        return f'<a class="cat-btn{cur}" href="{href}" style="--c:{color}" data-cat="{cid}"><span class="ci" data-icon="{icon_of[cid]}"></span><span class="cn">{e(name)}</span><span class="cc">{count}</span></a>'

    icon_of = {"all": "layout-grid", **{c["id"]: c["icon"] for c in categories}}
    out = item(f"{r}shop/", "all", "All products", len(products), "#9aa0a8")
    out += "".join(item(f"{r}category/{c['id']}/", c["id"], c["name"], c["count"], c["color"]) for c in categories)
    return out


def crumbs_ld(items):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [{"@type": "ListItem", "position": i + 1, "name": n, "item": SITE_URL + u} for i, (n, u) in enumerate(items)],
    }


def crumbs_html(r, items):
    parts = []
    for i, (n, u) in enumerate(items):
        if i == len(items) - 1:
            parts.append(f'<span aria-current="page">{e(n)}</span>')
        else:
            parts.append(f'<a href="{(r + u) if u else (r or "./")}">{e(n)}</a>')
    return '<span aria-hidden="true">/</span>'.join(parts)


# ---------------------------------------------------------------- shop + categories
def shop_main(r, categories, products, cat=None, grid=""):
    title = cat["name"] if cat else "All products"
    kicker = f"Category / {str(categories.index(cat) + 1).zfill(2)}" if cat else "Shop"
    tagline = cat["tagline"] if cat else "Advanced tech and gadgets sourced direct from manufacturers in China, inspected before shipping and delivered worldwide."
    media = (
        f'<div class="shop-hero-media"><img src="{r}{cat["photo"]}" alt="{e(cat["name"])}" width="1200" height="900" fetchpriority="high"></div>'
        if cat and cat.get("photo")
        else ""
    )
    count = cat["count"] if cat else len(products)
    links = cat_links(r, categories, products, cat["id"] if cat else "all")
    crumbs = [("Home", ""), ("Shop", "shop/")] + ([(cat["name"], f"category/{cat['id']}/")] if cat else [])
    return f"""  <main id="main">
    <section class="page-hero">
      <div class="container page-hero-grid{' has-media' if media else ''}">
      <div>
        <nav class="crumbs" aria-label="Breadcrumb">{crumbs_html(r, crumbs)}</nav>
        <p class="label" id="shop-kicker">{kicker}</p>
        <h1 id="shop-title">{e(title)}</h1>
        <p id="shop-tagline">{e(tagline)}</p>
      </div>
      {media}
      </div>
    </section>

    <section class="shop">
      <div class="container shop-layout">
        <aside class="shop-sidebar" aria-label="Categories">
          <h2>Categories</h2>
          <nav id="cat-list" aria-label="Product categories">{links}</nav>
        </aside>

        <div class="shop-main">
          <div class="shop-toolbar">
            <label class="search-wrap" id="search">
              <span class="sr-only">Search products</span>
              <span data-ui-icon="search"></span>
              <input type="search" id="shop-search" placeholder="Search {count} products" autocomplete="off" enterkeyhint="search">
            </label>
            <label class="sort-wrap"><span class="sr-only">Sort products</span>
              <select id="shop-sort">
                <option value="featured">Featured</option>
                <option value="az">Name A–Z</option>
                <option value="available">Available first</option>
              </select>
            </label>
          </div>
          <div class="status-filter" id="status-filter" role="group" aria-label="Availability">
            <button class="chip" type="button" data-status="all" aria-pressed="true">All</button>
            <button class="chip" type="button" data-status="available" aria-pressed="false">Available now</button>
            <button class="chip" type="button" data-status="coming" aria-pressed="false">Coming soon</button>
            <button class="chip" type="button" data-status="emerging" aria-pressed="false">Emerging</button>
          </div>
          <nav class="cat-chips" id="cat-chips" aria-label="Product categories">{links}</nav>
          <h2 class="sr-only">Products</h2>
          <p class="result-count" id="shop-count" aria-live="polite">{count} products</p>
          <div class="product-grid" id="shop-grid">{grid}</div>
          <div class="center-cta"><button class="btn btn-line" type="button" id="load-more" hidden>Load more</button></div>
          <p class="spec-note">Specifications shown are typical for each product type. Exact brand, model, price and minimum order are confirmed in your quotation.</p>
        </div>
      </div>
    </section>
  </main>"""


# ---------------------------------------------------------------- product page
def product_main(r, p, cat, products, related):
    specs_rows = "".join(f'<tr><th scope="row">Key feature</th><td>{e(s)}</td></tr>' for s in p["specs"])
    feats = "".join(f"<li><span>{e(s)}</span></li>" for s in p["specs"])
    rel = "".join(simple_card(r, x, cat) for x in related)
    crumbs = [("Home", ""), ("Shop", "shop/"), (cat["name"], f"category/{cat['id']}/"), (p["name"], f"product/{p['id']}/")]
    return f"""  <main id="main" class="page-pad">
    <div class="container" id="pdp">
      <nav class="crumbs" aria-label="Breadcrumb" id="crumbs">{crumbs_html(r, crumbs)}</nav>

      <section class="pdp" aria-labelledby="pdp-name">
        <div class="pdp-media">
          <div class="pdp-stage" id="pdp-stage">{art(r, p, cat, eager=True).replace('class="art photo"', 'class="art photo pdp-art"')}</div>
          <ul class="pdp-trust">
            <li><span data-ui-icon="check"></span>Inspected before shipment</li>
            <li><span data-ui-icon="check"></span>Samples on request</li>
            <li><span data-ui-icon="check"></span>OEM / private label</li>
            <li><span data-ui-icon="check"></span>Worldwide shipping</li>
          </ul>
        </div>

        <div class="pdp-info">
          <a class="pdp-cat" id="pdp-cat" href="{r}category/{cat['id']}/">{e(cat['name'])}</a>
          <h1 id="pdp-name">{e(p['name'])}</h1>
          <div class="pdp-meta"><span id="pdp-status"><span class="status {p['status']}">{STATUS_LABEL[p['status']]}</span></span><span class="pdp-code" id="pdp-code">{code(products, p)}</span></div>
          <p class="pdp-lead" id="pdp-lead">{e(p['desc'])}</p>

          <h2 class="pdp-sub">Highlights</h2>
          <ul class="pdp-highlights" id="pdp-highlights">{''.join(f'<li><strong>{e(s)}</strong></li>' for s in p['specs'])}</ul>

          <div class="pdp-price">
            <div><strong>Price on request</strong><span>Factory price, minimum order and shipping are confirmed in your quotation.</span></div>
          </div>

          <div class="pdp-buy">
            <div class="qty qty-lg" role="group" aria-label="Quantity">
              <button type="button" id="qty-minus" aria-label="Decrease quantity">−</button>
              <input type="number" id="qty" value="1" min="1" max="999999" inputmode="numeric" aria-label="Quantity">
              <button type="button" id="qty-plus" aria-label="Increase quantity">+</button>
            </div>
            <button class="btn" type="button" id="pdp-quote">Add to quote list</button>
            <button class="icon-btn" type="button" id="pdp-save" aria-label="Save" aria-pressed="false" data-ui-icon="heart"></button>
          </div>
          <div class="pdp-actions">
            <a class="btn btn-line btn-sm" id="pdp-wa" data-wa target="_blank" rel="noopener"><span data-ui-icon="brand-whatsapp"></span>Ask about this product</a>
            <button class="btn btn-line btn-sm" type="button" id="pdp-print">Print spec sheet</button>
            <button class="btn btn-line btn-sm" type="button" id="pdp-share">Copy link</button>
          </div>
        </div>
      </section>

      <nav class="pdp-tabs" aria-label="Product sections">
        <a href="#overview">Overview</a><a href="#specs">Specifications</a><a href="#sourcing">Sourcing &amp; shipping</a><a href="#faq">FAQ</a>
      </nav>

      <section class="pdp-section" id="overview" aria-labelledby="ov-title">
        <h2 id="ov-title">Overview</h2>
        <div class="pdp-two">
          <div id="pdp-overview"><p>{e(p['desc'])}</p><h3>Key features</h3><ul class="feature-list">{feats}</ul></div>
          <aside class="pdp-box">
            <h3>Ideal for</h3>
            <ul class="chips" id="pdp-ideal"></ul>
            <div id="pdp-notes"></div>
          </aside>
        </div>
      </section>

      <section class="pdp-section" id="specs" aria-labelledby="sp-title">
        <h2 id="sp-title">Specifications</h2>
        <table class="spec-table"><caption class="sr-only">Specifications</caption><tbody id="pdp-specs"><tr><th scope="row">Product</th><td>{e(p['name'])}</td></tr><tr><th scope="row">Type</th><td>{e(cat['name'])}</td></tr>{specs_rows}</tbody></table>
        <p class="spec-note">Typical specifications for this product type. Exact brand, model and specifications are confirmed in your quotation.</p>
      </section>

      <section class="pdp-section" id="sourcing" aria-labelledby="so-title">
        <h2 id="so-title">Sourcing &amp; shipping</h2>
        <table class="spec-table"><caption class="sr-only">Sourcing and shipping details</caption><tbody id="pdp-sourcing"></tbody></table>
      </section>

      <section class="pdp-section" id="faq" aria-labelledby="fq-title">
        <h2 id="fq-title">Frequently asked questions</h2>
        <div class="faq" id="pdp-faq"></div>
      </section>

      <section class="pdp-section" aria-labelledby="rl-title">
        <div class="pdp-related-head"><h2 id="rl-title">More in {e(cat['name'])}</h2><a class="btn btn-line btn-sm" id="pdp-more" href="{r}category/{cat['id']}/">View all {cat['count']}</a></div>
        <div class="product-grid related-4" id="pdp-related">{rel}</div>
      </section>
    </div>
  </main>"""


def related_for(p, products):
    same = [x for x in products if x["cat"] == p["cat"] and x["id"] != p["id"]]
    i = products.index(p)
    after = [x for x in same if products.index(x) > i]
    before = [x for x in same if products.index(x) < i]
    return (after + before)[:4]


# ---------------------------------------------------------------- info pages
TODO = '<mark class="todo">[TO COMPLETE: {}]</mark>'

INFO_PAGES = {
    "shipping-returns": {
        "title": "Shipping & Returns",
        "desc": "How SikandarTech quotes, inspects and ships orders from China, and how damaged or incorrect goods are handled.",
        "intro": "SikandarTech supplies products on quotation. Shipping costs, delivery times and after-sales terms are agreed in writing for each order before you pay.",
        "sections": [
            ("How an order works", [
                "Send your product list and quantities on WhatsApp or through the contact form.",
                "We reply with factory options, price, minimum order quantity, lead time and shipping cost to your country.",
                "Production starts once you confirm the quotation and the agreed payment terms.",
                "Goods are inspected before they leave the factory and you receive a photo or video report.",
            ]),
            ("Shipping methods", [
                "Express courier, air freight and sea freight, including consolidation of several suppliers into one shipment.",
                "Door-to-door delivery is available to most countries. The method and the cost are stated in your quotation.",
                "Delivery times depend on the method and the destination and are given in your quotation.",
                "Import duties, taxes and customs clearance: " + TODO.format("state who pays duties and taxes, for example the buyer, unless agreed otherwise"),
            ]),
            ("Damaged, missing or incorrect goods", [
                "Check your goods on arrival and tell us within " + TODO.format("number of days") + " days, with photos or a video of the packaging and the items.",
                "We compare the report with the pre-shipment inspection and work with the factory on a replacement, repair, partial refund or credit, depending on the case.",
                "Return shipping costs: " + TODO.format("state who pays return shipping and in which cases"),
            ]),
            ("Warranty", [
                "Products carry the manufacturer warranty. Its length and terms depend on the product and the factory and are confirmed in your quotation.",
                "Warranty claims are handled through SikandarTech with the manufacturer.",
            ]),
            ("Questions", ["Contact us on WhatsApp or by email before you order if anything about shipping or returns is unclear."]),
        ],
    },
    "privacy": {
        "title": "Privacy Policy",
        "desc": "What information the SikandarTech website stores, what you send us when you contact us, and how it is used.",
        "intro": "This page explains what happens to your information when you use this website.",
        "sections": [
            ("Information stored on your device", [
                "Your saved products and your quote list are stored in your own browser (local storage). They are not sent to us and you can clear them at any time by clearing your browser data.",
                "This website does not use advertising or analytics cookies.",
            ]),
            ("Information you send us", [
                "When you use the contact form, the quote list or a product enquiry, the website opens WhatsApp with a pre-filled message. Nothing is sent until you press send in WhatsApp.",
                "Messages you send on WhatsApp, WeChat, phone or email are used only to answer your enquiry, prepare quotations and handle your orders.",
                "If you submit a photo or video for the community page, it is used only as described on that page and only with your consent.",
            ]),
            ("Third-party services", [
                "WhatsApp, Instagram, TikTok and Facebook links open those services, which have their own privacy policies.",
                "Website hosting: " + TODO.format("name of your hosting provider, for example GitHub Pages"),
            ]),
            ("Your rights and contact", [
                "To ask what information we hold about you, or to have it deleted, contact us at the email address below.",
                "Contact for privacy questions: " + TODO.format("privacy contact email"),
                "Last updated: " + TODO.format("date"),
            ]),
        ],
    },
    "terms": {
        "title": "Terms of Service",
        "desc": "Terms for using the SikandarTech website and for quotations and orders placed with SikandarTech.",
        "intro": "These terms cover the use of this website. Each order is also governed by the quotation and agreement you confirm with us.",
        "sections": [
            ("About this website", [
                "The products on this website show the types of technology SikandarTech can source. Specifications are typical for each product type. The exact brand, model, specifications, price and minimum order are confirmed in your quotation.",
                "Product photos show the product type and may differ from the item supplied.",
                "There are no online payments on this website. Prices are given by quotation only.",
            ]),
            ("Quotations and orders", [
                "A quotation is valid for the period stated on it. Prices can change with factory costs, exchange rates and shipping rates.",
                "An order is confirmed when both sides agree the quotation in writing and the agreed payment terms are met.",
                "Payment terms: " + TODO.format("deposit and balance terms, accepted payment methods"),
            ]),
            ("Responsibilities", [
                "You are responsible for checking that products can be imported and sold in your country, including any certification required. We can request compliance documents from the factory.",
                "Limitation of liability: " + TODO.format("your liability terms, reviewed by a legal adviser"),
            ]),
            ("Company details", [
                "Business name and registration: " + TODO.format("legal business name and registration number"),
                "Business address: " + TODO.format("full business address in Guangzhou"),
                "Governing law: " + TODO.format("governing law and jurisdiction"),
                "Last updated: " + TODO.format("date"),
            ]),
        ],
    },
}


def info_main(r, slug, d):
    secs = "".join(
        f'<section class="info-section"><h2>{e(h)}</h2><ul>{"".join(f"<li>{x}</li>" for x in items)}</ul></section>'
        for h, items in d["sections"]
    )
    crumbs = [("Home", ""), (d["title"], f"{slug}/")]
    return f"""  <main id="main" class="page-pad">
    <article class="container info-page">
      <nav class="crumbs" aria-label="Breadcrumb">{crumbs_html(r, crumbs)}</nav>
      <p class="label">SikandarTech</p>
      <h1>{e(d['title'])}</h1>
      <p class="info-intro">{e(d['intro'])}</p>
      {secs}
      <div class="info-contact"><p>Questions about this page?</p><a class="btn" data-wa target="_blank" rel="noopener"><span data-ui-icon="brand-whatsapp"></span>Ask on WhatsApp</a></div>
    </article>
  </main>"""


# ---------------------------------------------------------------- redirects
REDIRECT_SHOP = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Shop | SikandarTech</title>
  <meta name="robots" content="noindex">
  <link rel="canonical" href="https://sikandartech.com/shop/">
  <script>
    var q = new URLSearchParams(location.search), c = q.get("cat"); q.delete("cat");
    var s = q.toString();
    location.replace((c && /^[a-z0-9-]+$/.test(c) ? "category/" + c + "/" : "shop/") + (s ? "?" + s : "") + location.hash);
  </script>
  <noscript><meta http-equiv="refresh" content="0; url=shop/"></noscript>
</head>
<body><p><a href="shop/">Continue to the SikandarTech shop</a></p></body>
</html>
"""

REDIRECT_PRODUCT = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Product | SikandarTech</title>
  <meta name="robots" content="noindex">
  <link rel="canonical" href="https://sikandartech.com/shop/">
  <script>
    var id = new URLSearchParams(location.search).get("id");
    location.replace(id && /^[a-z0-9-]+$/.test(id) ? "product/" + id + "/" : "shop/");
  </script>
  <noscript><meta http-equiv="refresh" content="0; url=shop/"></noscript>
</head>
<body><p><a href="shop/">Continue to the SikandarTech shop</a></p></body>
</html>
"""


def not_found(cat_by_id):
    # Served by the host for any missing path, at any depth, so links resolve from a <base>.
    base = """
  <script>(function(){var h=location.hostname,p=location.pathname.split("/")[1];document.write('<base href="'+(/github\\.io$/.test(h)&&p?"/"+p+"/":"/")+'">')})()</script>"""
    h = head("", "Page not found | SikandarTech", "The page you were looking for does not exist.", "404.html", robots="noindex").replace(
        "<head>", "<head>" + base, 1
    ).replace('<link rel="canonical" href="https://sikandartech.com/404.html">\n  ', "")
    main = """  <main id="main" class="page-pad">
    <div class="container state-page">
      <p class="label">Error 404</p>
      <h1>Page not found</h1>
      <p>The page may have moved, or the link may be mistyped. Search the shop, or tell us what you are looking for and we will source it.</p>
      <form class="state-search" action="shop/" role="search">
        <label class="search-wrap"><span class="sr-only">Search products</span><span data-ui-icon="search"></span><input type="search" name="q" placeholder="Search products" enterkeyhint="search"></label>
        <button class="btn" type="submit">Search</button>
      </form>
      <div class="state-actions"><a class="btn btn-line" href="./">Home</a><a class="btn btn-line" href="shop/">Browse all products</a><a class="btn btn-line" data-wa target="_blank" rel="noopener">Ask on WhatsApp</a></div>
    </div>
  </main>"""
    return page("", h, "state", main, cat_by_id)


# ---------------------------------------------------------------- shared header/footer in hand-written pages
def sync_partials(site, rel, cat_by_id, active):
    path = os.path.join(site, rel)
    text = open(path).read()
    text = re.sub(r"<!-- @header.*?<!-- /@header -->", lambda m: header("", active), text, flags=re.S)
    text = re.sub(r"<!-- @footer.*?<!-- /@footer -->", lambda m: footer("", cat_by_id), text, flags=re.S)
    open(path, "w").write(text)


# ---------------------------------------------------------------- entry point
def build(site, categories, products):
    cat_by_id = {c["id"]: c for c in categories}
    urls = ["", "shop/", "ugc.html"]

    # Shop
    h = head(
        "../", "Shop All Tech & Gadgets | SikandarTech",
        f"Browse {len(products)} advanced tech products in {len(categories)} categories: AI gadgets, computing, wearables, audio, cameras, drones, smart home and more. Request a factory quote.",
        "shop/",
        ld=[crumbs_ld([("Home", ""), ("Shop", "shop/")])],
    )
    write(site, "shop/index.html", page("../", h, "shop-page", shop_main("../", categories, products), cat_by_id, ["shop.js"], "shop", ' data-cat="all"'))

    # Categories
    for c in categories:
        r = "../../"
        items = [p for p in products if p["cat"] == c["id"]]
        path = f"category/{c['id']}/"
        desc = trim(f"{c['tagline']} Browse {c['count']} products in {c['name']}, sourced direct from manufacturers in China with inspection and worldwide shipping.")
        ld = [
            crumbs_ld([("Home", ""), ("Shop", "shop/"), (c["name"], path)]),
            {
                "@context": "https://schema.org", "@type": "CollectionPage", "name": c["name"], "description": c["tagline"], "url": SITE_URL + path,
                "mainEntity": {"@type": "ItemList", "numberOfItems": len(items), "itemListElement": [
                    {"@type": "ListItem", "position": i + 1, "url": f"{SITE_URL}product/{p['id']}/", "name": p["name"]} for i, p in enumerate(items)]},
            },
        ]
        h = head(r, f"{c['name']} | SikandarTech", desc, path, c.get("photo", DEFAULT_OG), ld=ld)
        grid = "".join(simple_card(r, p, c) for p in items)
        write(site, path + "index.html", page(r, h, "shop-page", shop_main(r, categories, products, c, grid), cat_by_id, ["shop.js"], "shop", f' data-cat="{c["id"]}"'))
        urls.append(path)

    # Products
    for p in products:
        r = "../../"
        c = cat_by_id[p["cat"]]
        path = f"product/{p['id']}/"
        desc = trim(f"{p['desc']} Key features: {', '.join(p['specs'][:3])}. Request a factory quote from SikandarTech.")
        prod_ld = {
            "@context": "https://schema.org", "@type": "Product", "name": p["name"], "description": p["desc"],
            "sku": code(products, p), "category": c["name"], "url": SITE_URL + path,
            "additionalProperty": [{"@type": "PropertyValue", "name": "Key feature", "value": s} for s in p["specs"]]
            + [{"@type": "PropertyValue", "name": "Availability", "value": STATUS_SCHEMA[p["status"]]}],
        }
        if p.get("photo"):
            prod_ld["image"] = SITE_URL + p["photo"]
        ld = [prod_ld, crumbs_ld([("Home", ""), ("Shop", "shop/"), (c["name"], f"category/{c['id']}/"), (p["name"], path)])]
        h = head(r, f"{p['name']} | SikandarTech", desc, path, p.get("photo") or c.get("photo") or DEFAULT_OG, ld=ld)
        main = product_main(r, p, c, products, related_for(p, products))
        write(site, path + "index.html", page(r, h, "shop-page pdp-page", main, cat_by_id, ["product.js"], "shop", f' data-product="{p["id"]}"'))
        urls.append(path)

    # Info pages
    for slug, d in INFO_PAGES.items():
        h = head("../", f"{d['title']} | SikandarTech", d["desc"], f"{slug}/", ld=[crumbs_ld([("Home", ""), (d["title"], f"{slug}/")])])
        write(site, f"{slug}/index.html", page("../", h, "info", info_main("../", slug, d), cat_by_id))
        urls.append(f"{slug}/")

    write(site, "404.html", not_found(cat_by_id))
    write(site, "products.html", REDIRECT_SHOP)
    write(site, "product.html", REDIRECT_PRODUCT)
    sync_partials(site, "index.html", cat_by_id, "")
    sync_partials(site, "ugc.html", cat_by_id, "community")

    with open(os.path.join(site, "sitemap.xml"), "w") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        for u in urls:
            f.write(f"  <url><loc>{SITE_URL}{u}</loc></url>\n")
        f.write("</urlset>\n")
    return len(urls)
